Extension { #name : #MonthOfYear }

{ #category : #'*Chalten-Core-Roman' }
MonthOfYear class >> aprilOf: aYear [

	^self year: aYear month: aYear calendar april
]

{ #category : #'*Chalten-Core-Roman' }
MonthOfYear class >> augustOf: aYear [

	^self year: aYear month: aYear calendar august
]

{ #category : #'*Chalten-Core-Roman' }
MonthOfYear class >> decemberOf: aYear [

	^self year: aYear month: aYear calendar december
]

{ #category : #'*Chalten-Core-Roman' }
MonthOfYear class >> februaryOf: aYear [

	^self year: aYear month: aYear calendar february
]

{ #category : #'*Chalten-Core-Roman' }
MonthOfYear class >> januaryOf: aYear [

	^self year: aYear month: aYear calendar january
]

{ #category : #'*Chalten-Core-Roman' }
MonthOfYear class >> julyOf: aYear [

	^self year: aYear month: aYear calendar july
]

{ #category : #'*Chalten-Core-Roman' }
MonthOfYear class >> juneOf: aYear [

	^self year: aYear month: aYear calendar june
]

{ #category : #'*Chalten-Core-Roman' }
MonthOfYear class >> marchOf: aYear [

	^self year: aYear month: aYear calendar march
]

{ #category : #'*Chalten-Core-Roman' }
MonthOfYear class >> mayOf: aYear [

	^self year: aYear month: aYear calendar may
]

{ #category : #'*Chalten-Core-Roman' }
MonthOfYear class >> novemberOf: aYear [

	^self year: aYear month: aYear calendar november
]

{ #category : #'*Chalten-Core-Roman' }
MonthOfYear class >> octoberOf: aYear [

	^self year: aYear month: aYear calendar october
]

{ #category : #'*Chalten-Core-Roman' }
MonthOfYear class >> septemberOf: aYear [

	^self year: aYear month: aYear calendar september
]
