Extension { #name : #MonthOfYear }

{ #category : #'*Chalten-Core-Hebrew' }
MonthOfYear class >> adarIIOf: aYear [

	^self year: aYear month: HebrewCalendar adarII
]

{ #category : #'*Chalten-Core-Hebrew' }
MonthOfYear class >> adarIOf: aYear [

	^self year: aYear month: HebrewCalendar adarI
]

{ #category : #'*Chalten-Core-Hebrew' }
MonthOfYear class >> adarOf: aYear [

	^self year: aYear month: HebrewCalendar adar
]

{ #category : #'*Chalten-Core-Hebrew' }
MonthOfYear class >> avOf: aYear [

	^self year: aYear month: HebrewCalendar av
]

{ #category : #'*Chalten-Core-Hebrew' }
MonthOfYear class >> elulOf: aYear [

	^self year: aYear month: HebrewCalendar elul
]

{ #category : #'*Chalten-Core-Hebrew' }
MonthOfYear class >> iyyarOf: aYear [

	^self year: aYear month: HebrewCalendar iyyar
]

{ #category : #'*Chalten-Core-Hebrew' }
MonthOfYear class >> kislevOf: aYear [

	^self year: aYear month: HebrewCalendar kislev
]

{ #category : #'*Chalten-Core-Hebrew' }
MonthOfYear class >> marheshvanOf: aYear [

	^self year: aYear month: HebrewCalendar marheshvan
]

{ #category : #'*Chalten-Core-Hebrew' }
MonthOfYear class >> nisanOf: aYear [

	^self year: aYear month: HebrewCalendar nisan
]

{ #category : #'*Chalten-Core-Hebrew' }
MonthOfYear class >> shevatOf: aYear [

	^self year: aYear month: HebrewCalendar shevat
]

{ #category : #'*Chalten-Core-Hebrew' }
MonthOfYear class >> sivanOf: aYear [

	^self year: aYear month: HebrewCalendar sivan
]

{ #category : #'*Chalten-Core-Hebrew' }
MonthOfYear class >> tammuzOf: aYear [

	^self year: aYear month: HebrewCalendar tammuz
]

{ #category : #'*Chalten-Core-Hebrew' }
MonthOfYear class >> tevetOf: aYear [

	^self year: aYear month: HebrewCalendar tevet
]

{ #category : #'*Chalten-Core-Hebrew' }
MonthOfYear class >> tishriOf: aYear [

	^self year: aYear month: HebrewCalendar tishri
]
